"""Create the working notebook for a problem.

Cells carry tags so the publisher can assemble a post deterministically instead of
guessing which cells are prose and which are scratch work:

    meta        problem header - regenerated by the publisher, never published as-is
    statement   the LeetCode statement, kept local (not republished)
    cue         scenario + clue from your sheet (the post shows this once, in its intro)
    approach    your write-up; this becomes the body of the blog section
    solution    the accepted solution
    tests       driver cell whose output is published as a result block
    complexity  time/space notes

Add `no-publish` to any cell you want kept out of the post.
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from . import config, leetcode_api
from .util import slugify

NB_FORMAT = {"nbformat": 4, "nbformat_minor": 5}

APPROACH_PLACEHOLDER = """## Approach

<!-- Written here, published to the blog. Replace this list with the real reasoning. -->

- **Idea:**
- **Why this pattern fits:**
- **Walkthrough:**
"""

COMPLEXITY_PLACEHOLDER = """## Complexity

- **Time:** `O(?)` -
- **Space:** `O(?)` -
"""


def _markdown(source: str, tags: list[str]) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {"tags": tags},
        "source": source.splitlines(keepends=True),
    }


def _code(source: str, tags: list[str]) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"tags": tags},
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


def notebook_path(row: sqlite3.Row, topic_position: int) -> Path:
    """leetcode/solutions/01-arrays/two-pointers/two-sum.ipynb"""
    return (
        config.SOLUTIONS_DIR
        / f"{topic_position + 1:02d}-{row['topic_slug']}"
        / row["pattern_slug"]
        / f"{row['lc_slug'] or slugify(row['title'])}.ipynb"
    )


def build_notebook(row: sqlite3.Row, question: dict | None) -> dict:
    """Assemble the notebook document for one problem."""
    difficulty = row["difficulty"] or "Unknown"
    number = row["lc_id"] or (question or {}).get("questionFrontendId") or "?"
    tags = ", ".join(t["name"] for t in (question or {}).get("topicTags") or []) or "-"

    header = (
        f"# {number}. {row['title']}\n\n"
        f"| | |\n|---|---|\n"
        f"| **Difficulty** | {difficulty} |\n"
        f"| **Topic** | {row['topic_name']} |\n"
        f"| **Pattern** | {row['pattern_name']} |\n"
        f"| **LeetCode tags** | {tags} |\n"
        f"| **Link** | [{row['lc_slug']}]({row['url']}) |\n"
    )

    cells = [_markdown(header, ["meta", "no-publish"])]

    statement = leetcode_api.statement_to_markdown(question)
    if statement:
        cells.append(
            _markdown(
                "## Problem\n\n" + statement + "\n",
                ["statement", "no-publish"],
            )
        )

    cue_parts = []
    if row["scenario"]:
        cue_parts.append("**When this pattern applies**\n\n" + row["scenario"])
    if row["clue"]:
        cue_parts.append("**Clue in the wording**\n\n" + row["clue"])
    if cue_parts:
        cells.append(
            _markdown(
                "## Pattern cue\n\n" + "\n\n".join(cue_parts) + "\n",
                # The post carries this once in its intro, so it stays out of the section.
                ["cue", "no-publish"],
            )
        )

    cells.append(_markdown(APPROACH_PLACEHOLDER, ["approach"]))
    cells.append(_code(leetcode_api.python_stub(question), ["solution"]))
    cells.append(
        _code(
            "# Quick checks - this cell's output is published as the result block.\n"
            "s = Solution()\n"
            "# print(s.method(...))\n",
            ["tests"],
        )
    )
    cells.append(_markdown(COMPLEXITY_PLACEHOLDER, ["complexity"]))

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
            "dsa_bot": {
                "problem_id": row["id"],
                "lc_slug": row["lc_slug"],
                "url": row["url"],
                "topic": row["topic_name"],
                "pattern": row["pattern_name"],
                "difficulty": difficulty,
            },
        },
        **NB_FORMAT,
    }


def create_for_problem(
    conn: sqlite3.Connection, row: sqlite3.Row, overwrite: bool = False
) -> Path:
    """Write the notebook for `row` and record its path. Existing work is never clobbered."""
    topic = conn.execute(
        "SELECT position FROM topics WHERE slug = ?", (row["topic_slug"],)
    ).fetchone()
    path = notebook_path(row, topic["position"] if topic else 0)

    if path.exists() and not overwrite:
        conn.execute(
            "UPDATE problems SET notebook_path = ? WHERE id = ?",
            (str(path.relative_to(config.REPO_ROOT)), row["id"]),
        )
        return path

    question = leetcode_api.fetch_question(row["lc_slug"])
    if question and question.get("difficulty") and row["difficulty"] == "Unknown":
        conn.execute(
            "UPDATE problems SET difficulty = ?, lc_id = ? WHERE lc_slug = ?",
            (question["difficulty"], question.get("questionFrontendId"), row["lc_slug"]),
        )
        row = dict(row) | {
            "difficulty": question["difficulty"],
            "lc_id": question.get("questionFrontendId"),
        }

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(build_notebook(row, question), indent=1, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    conn.execute(
        "UPDATE problems SET notebook_path = ? WHERE id = ?",
        (str(path.relative_to(config.REPO_ROOT)), row["id"]),
    )
    return path
